# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:

 - 5.5

 - 5.6

 - 7.0

 - 7.1

 - 7.2

 - hhvm

# Commands to be run before your environment runs.
before_script:

 - composer self-update

 - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.

script: phpunit

# allow_failures: Allow this build to fail under the specified environments.

# fast_finish: If your build fails do not continue trying to build, just stop.

matrix:

 allow_failures:

   - php: 5.6

   - php: hhvm

 fast_finish: true

# Customize when the notification emails are sent.

notifications:

   on_success: always

   on_failure: always

Here I’ve added the PHP versions that are allowed for the projects.

before_script allows you to run command before the environment actually executes.

allow_failures contains the conditions that allow your build to fail.

notifications will notify you in all scenarios of build success or failure.

If you are using Symfony 3, you can add this script provided by Antonio Jiménez

# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
 - mysql

# Cache composer packages so "composer install" is faster
cache:
 directories:
   - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
 # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
 fast_finish: true
 include:
   - php: 5.5
   - php: 5.6
   - php: 7.0
   - php: hhvm
 allow_failures:
   - php: hhvm

# Define an environment variable
#env:
# - SYMFONY_VERSION="3.0.*" DB=mysql

# Update composer
before-install:
 - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
 - composer install
 - cp app/config/parameters.yml.dist app/config/parameters.yml
 - php bin/console doctrine:database:create --env=test
 - php bin/console doctrine:schema:create --env=test
 - php bin/console doctrine:fixtures:load -n --env=test

# Run script
script:
 - phpunit

# After a build, send email notification with the build results
notifications:
 email: harmon.singh@my.jcu.edu.au
